### ISSUE TITLE
when applicationWillEnterForeground from Background ,app crash

### ISSUE THREAD

**Issue by xbitlabs** [Loadex/MessageBanner#9]
The view hierarchy is not prepared for the constraint: 
<NSLayoutConstraint:0x166bbdd0 _UILayoutGuide:0x166baa20.bottom == MBLMessageBannerView:0x16518cb0.top>
	When added to a view, the constraint's items must be descendants of that view (or the view itself). This will crash if the constraint needs to be resolved before the view hierarchy is assembled. Break on -[UIView _viewHierarchyUnpreparedForConstraint:] to debug.
2015-05-27 11:44:17.971 Weishitong[994:237847] *** Assertion failure in -[UILayoutContainerView _layoutEngine_didAddLayoutConstraint:roundingAdjustment:mutuallyExclusiveConstraints:], /SourceCache/UIKit/UIKit-3318.16.21/NSLayoutConstraint_UIKitAdditions.m:560

**Comment by xbitlabs** [comment]
The view hierarchy is not prepared for the constraint: <NSLayoutConstraint:0x166bbdd0 _UILayoutGuide:0x166baa20.bottom == MBLMessageBannerView:0x16518cb0.top>

**Comment by Loadex** [comment]
Thanks for the issue, can you give me some step to reproduce please ?

**Comment by xbitlabs** [comment]
I use Reachability lib(https://github.com/tonymillion/Reachability) to notification the network status.When network reachable，show a messagebanner.

1、Tap app icon，launching app
2、Press Home，app did enter background
3、Tap app icon again,app will enter foreground,network reachable , show the MessageBanner,app crash.

**Comment by Loadex** [comment]
I will look into it tonight, thanks for the feedback !
I'll post here to let you know when fixed.

**Comment by Loadex** [comment]
@xbitlabs Where did you put your reachability code, can you provide me your implementation ?

**Comment by xbitlabs** [comment]
override func viewDidLoad() {
        super.viewDidLoad()
        NSNotificationCenter.defaultCenter().addObserver(self, selector: "unrechableNotification:", name: N_UNRECHABLE, object: nil)
}
func unrechableNotification(notification:NSNotification){
        msg.error( self, title: "嘿嘿", subTitle: "无网络连接")
 }
+(void)error:(UIViewController*)defaultViewController title:(NSString *)title subTitle:(NSString *)subTitle{
    [MBLMessageBanner showMessageBannerInViewController:defaultViewController title:title subtitle:subTitle type:MBLMessageBannerTypeError atPosition:MBLMessageBannerPositionTop];
}

#import <Foundation/Foundation.h>
#include "ReachabilityManager.h"

static ReachabilityManager *reachabilityManager;

@implementation ReachabilityManager

+(ReachabilityManager*)shareInstance{
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        reachabilityManager = [[ReachabilityManager alloc]init];
    });
    return reachabilityManager;
}
-(void)setup:(NSString *)reachabilityWithHostname reachableBlock:(NetworkReachable)reachableBlock unreachableBlock:(NetworkUnreachable)unreachableBlock{
    
    reachability = [Reachability reachabilityWithHostname:reachabilityWithHostname];
    reachability.unreachableBlock = unreachableBlock;
    reachability.reachableBlock = reachableBlock;
    [reachability startNotifier];
}
-(BOOL)isReachable{
    return reachability.isReachable;
}
-(void)dealloc{
    [reachability stopNotifier];
    reachability = nil;
}
@end

//reachable

      let reachable : ReachabilityManager = ReachabilityManager.shareInstance()
        reachable.setup("www.163.com",
            reachableBlock: {(reach:Reachability!) in
                println("网络可用")
                SocketService.sharedInstance().connect()
                NSNotificationCenter.defaultCenter().postNotificationName(N_RECHABLE, object: nil)
            },
            unreachableBlock: {(reach:Reachability!)in
                println("网络不可用")
                NSNotificationCenter.defaultCenter().postNotificationName(N_UNRECHABLE, object: nil)
        })

**Comment by Loadex** [comment]
I've implemented something close to your test and i don't see any crashes on message banner, here is what i did on the demo project : 

```@property (nonatomic, strong, readwrite) Reachability* reach;```

```- (void)viewDidLoad
{
    [super viewDidLoad]; 
    [self test];
...
}```

```
- (void)test {
    self.reach = [Reachability reachabilityWithHostname:@"www.google.com"];

    // Set the blocks
    self.reach.reachableBlock = ^(Reachability*reach)
    {
        [self popMeOne:nil];
    };

    self.reach.unreachableBlock = ^(Reachability*reach)
    {
        [self popMeOne:nil];
    };
    [self.reach startNotifier];
}
```

Procedure to test : 
Launch the app -> Press Home -> Come back to app, I checked with breakpoint, no trigger on both block.
So i tried : 
Launch the app -> Press Home -> Cut my wifi -> Come back to app. Everything is fine, i see the banner an no exceptions

Did i do my tests wrong ?

**Comment by xbitlabs** [comment]
Right

**Comment by xbitlabs** [comment]
Let me check my code

**Comment by Loadex** [comment]
Sure, if you want to send me a zip of your project i can help you check this too.

**Comment by Loadex** [comment]
@xbitlabs Is this issue resolved ?

**Comment by xbitlabs** [comment]
Has not been resolved, not find a reason why
